name: Storytel CI

on:
  pull_request:
    types: [opened,reopened]

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI builds
        run: |
          curl -X POST \
          -H 'Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}' \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/json' \
          -d "{\"branch\":\"${{ github.head_ref }}\"}" \
          https://circleci.com/api/v2/project/gh/${GITHUB_REPOSITORY}/pipeline
